groups:
    - roles/people/indieisaconcept
attributes:

    git:
        name: Jonathan Barnett
        email: jonathan.barnett@news.com.au

    profile:
        aliases:
            vdir: cd /Users/barnettj/Sites/development/projects/news/git/tcog/tcog-vagrant

    authorization:
        sudo:
            users:
                - barnettj
            passwordless: true
            include_sudoers_d: true


