groups:
    - templates/people/indieisaconcept

recipes:
    mac_os_x:
        - osxdefaults::set_computer_name

attributes:

    git:
        name: indieisaconcept
        email: me@indieisaconcept.com

    osxdefaults:
        computername: indieisaconcept